# Site settings
title: Walker
subtitle: Without Soul
email: 814663095@qq.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://zhangxiaoqiang.win/" # the base hostname & protocol for your site
author: "Zhang Xiaoqiang"
street_address: Binjiang
city: Hangzhou Zhejiang
state: China
zip_code: 310053
country: Shandong Linyi
phone: 187****2341

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Zomnus/PersonalPages
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
