# Site settings
title: Walker
subtitle: Without Soal
email: 814663095@qq.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://andrewbanchich.gitlab.io" # the base hostname & protocol for your site
author: Zhang Xiaoqiang
street_address: Binjiang
city: Hangzhou Zhejiang
state: China
zip_code: 310053
country: Shandong Linyi
phone: 187****2341

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
